import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}

// 👇 これを追加（先ほど作った部品をインポート）
import TentMenu from "@/components/TentMenu"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "trofa | スケジュールを、アトラクションに。",
  description: "スケジュールアプリtrofaの開発会社コーポレートサイト",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        {/* 👇 これを追加（ウェブサイト全体にメニューボタンを配置） */}
        <TentMenu />
        
        {children}
      </body>
    </html>
  );
}